Repository nss-day-cohort-51/nss-day-cohort-51.github.io, pull requests merged in 2022-01, with the labels that each got.

#142 Mw fix modal width on mobile viewport
  src/components/DevCard.js
  src/components/MediaButtons.js
  src/styles/modal.scss
Labels: fix

#151 Description Section: Rogue white line showing on right of SVG design mw-fix-Description-section-147 Redrew the background SVG for the Desc…
  src/images/description-BG-swoop.svg
  src/styles/description.scss
  src/styles/devlist.scss
Labels: fix

#155 Mw fix alien coming soon alignment
  public/alien-coming-soon-340w-235h.gif
  public/alien-coming-soon-340w-235h.png
  src/components/MediaButtons.js
  src/images/alien-coming-soon-340w-235h.gif
  src/styles/modal.scss
Labels: fix

#157 updated headshot
  public/api/database.json
  src/images/morgan.jpg
  src/images/morgan.png
Labels: update

#161 mw-update-MichaelWright-portfolio-link update Michael Wright's portfo…
  public/api/database.json
  pull_request_template.md
Labels: update

#164 updated links on dev cards
  public/api/database.json
Labels: update

#169 mw-Logo-resize-168 uploaded the resized logo image as logo.svg; it's …
  public/logo192.png
  public/logo512.png
  src/components/Description.js
  src/components/Fav.js
  src/images/logo.png
  src/images/logo.svg
Labels: enhancement

#170 Mw add google analytics 107
  public/index.html
  src/components/Fav.js
Labels: enhancement

#174 ss-hide-hearts-173:
  public/alien-coming-soon-340w-235h.gif
  public/index.html
  src/components/DevCard.js
  src/images/alien-coming-soon-340w-235h.png
  src/images/favorite-border.svg
  src/images/favorite.svg
  src/styles/devlist.scss
  src/styles/fav-alt.scss
  src/styles/fav.scss
  src/styles/logo192.png
Labels: bug
